### ISSUE TITLE
Some OpenJDK 7 packages do not include JavaFX

### ISSUE THREAD

**Issue by MichaelJAllen** [scalafx/scalafx#141]
I've just discovered that, for example, the _Ubuntu_ `openjdk-7-jdk` & `openjdk-7-jre` packages _do not_ include _JavaFX_. I think this may affect _OpenJDK_ packages on other _Linux_-based systems (I'm not sure whether _OpenJDK 8_ is affected, since it seems that none of the major distros have gotten around to packaging it yet).

Unfortunately, it also appears that _JavaFX_ isn't available as a dependency in any _Maven_ or _Ivy_ repositories, so we can't simply solve the problem that way. A quick and dirty solution would be for the build to check for the presence of `$JAVA_HOME/lib/jfxrt.jar` and give a suitable error message if it's not present.

Without such a test, all attempts to compile, test or run will result in a vast number of errors, the root cause being the failure to `import javafx.`_xyz_ in just about every source file. That would likely scare off many potential users.

If this affects you, download _OpenJDK 7_ as a tarball directly from _Oracle_ and install it manually.

**Comment by Shadow53** [comment]
Some distributions may offer JavaFX inside of another package: for instance, Arch Linux offers it through the [java-openjfx](https://www.archlinux.org/packages/?q=java-openjfx) package. It also appears that Ubuntu (now) has it in the [openjfx](http://packages.ubuntu.com/xenial/openjfx) package. Users may check that first rather than go to downloading a tarball.

**Comment by Jeansen** [comment]
Shouldn't that one be closed? I think it is obsolete ....

**Comment by jpsacha** [comment]
JavaFX 11 and newer are distributed separately from JVM and are available in Maven repos. So practically this issue is obsolete.
