### ISSUE TITLE
ScalaFx not compatible in Mac M1

### ISSUE THREAD

**Issue by saulpalv** [scalafx/scalafx#365]
dependencies for OSX aarch64 can't be resolved, so metals import fails, is there a way to specify JavaFX modules included on the JDK or downloaded manually?

**Comment by jpsacha** [comment]
JavaFX 16 and older did not provide dependency for `aarch64 `.
Going to JavaFX 17, that does provide dependency, is problematic due to SBT bug:
https://github.com/sbt/sbt/issues/6564

In any case, in 16 and earlier, you can select native binaries in SBT using `classifier`:
```sbt
"org.openjfx" % "javafx-graphics" % javaFXVersion classifier osName
```
where variable `osName` is something like `mac`, `win`, `linux`.

For Java 17, may be able to use `mac-aarch64`, but currently SBT bug https://github.com/sbt/sbt/issues/6564 is preventing using 17 and newer. ScalaFX does not yet officially support JavaFX due that bug (https://github.com/scalafx/scalafx/issues/362)

**Comment by saulpalv** [comment]
just worked and didn't know why, just set zulu 17 jdk with included javafx modules, created a new ScalaFX project using ScalaFX.g8 template and worked

![image](https://user-images.githubusercontent.com/19735362/134051191-d620e93a-793f-4182-880a-4657d6150190.png)

**Comment by saulpalv** [comment]
> JavaFX 16 and older did not provide dependency for `aarch64 `.
> Going to JavaFX 17, that does provide dependency, is problematic due to SBT bug:
> [sbt/sbt#6564](https://github.com/sbt/sbt/issues/6564)
> 
> In any case, in 16 and earlier, you can select native binaries in SBT using `classifier`:
> 
> ```scala
> "org.openjfx" % "javafx-graphics" % javaFXVersion classifier osName
> ```
> 
> where variable `osName` is something like `mac`, `win`, `linux`.
> 
> For Java 17, may be able to use `mac-aarch64`, but currently SBT bug [sbt/sbt#6564](https://github.com/sbt/sbt/issues/6564) is preventing using 17 and newer. ScalaFX does not yet officially support JavaFX due that bug (#362)

thank you for your response, i can confirm the info you gave, oracle started providing official Mac M1 build for JDK since JDK 17, the same goes for gluon on OpenJFX, but given that the project worked with Zulu's JDK included JavaFX modules, anyone can just install the Zulu/Liberica JDK for development

**Comment by saulpalv** [comment]
for
