### ISSUE TITLE
[Help] Release  21.0.3 version of javaFX binding

### ISSUE THREAD

**Issue by thinkiny** [scalafx/scalafx#409]
There's a bug on macOS in JavaFX 21 causing the app to freeze at startup. Since 21 is a long-term support version, will you release a ScalaFX version corresponding to JavaFX 21.0.3?

issue link:
https://stackoverflow.com/questions/77223963/javafx-window-takes-a-while-to-load-and-getting-an-error-in-eclipse
https://bugs.openjdk.org/browse/JDK-8315657

**Comment by jpsacha** [comment]
There are no plans to release updates for past versions just to update dependencies, since there are ways to update dependencies at the point of use. 

You have a couple of options. The key is to remember that while Java and JavaFX number follow each other, this does not mean that, for instance, JavaFX 22 requires Java 22. You run JavaFX 22 with Java 21, I think all that way back to Java 17. 

My recommendation is to use the latest release JavaFX 22 and ScalaFX 22.0.0-R33. 

If you need to Use JavaFX 21.x you can "force" the dependency on the specific version of JavaFX, like 21.0.3. Just make sure that you match JavaFX and ScalaFX major version, use ScalaFX 21.x with JavaFX 21.x . In SBT you can "force" the version with something like this in your `build.sbt`:

```SBT
libraryDependencies ++= javafxModules

lazy val javafxModules =
  Seq("base", "controls", "fxml", "graphics", "media", "swing", "web")
    .map(m => "org.openjfx" % s"javafx-$m" % "21.0.3")
```
Similar if you want to use JavaFX 22.0.1 with ScalaFX 22.0.0-R33.
